### ISSUE TITLE
[Test] - Bot telegram

### ISSUE THREAD

**Issue by jvegax** [jvegax/decide#16]
| Estado  | Tipo  | Responsable            | Prioridad |
| ------- | ----- | ---------------------- | --------- |
| *En progreso* | *Test* | *LuisUsrDev, joscacgom* |     *1*  |

### Descripción:
Se pide realizar test que comprueben que el bot de telegram se lanza correctamente al 

- [ ] Creacion votacion
- [ ] Cierre de votacion
- [ ] Recuento de votacion
- [ ] Uso de comandos de telegram por parte del usuario 

### Solución Adoptada:
En curso.

### Posibles Soluciones:
- Comprobar distintas librerias que puedan probar esas funcionalidades

**Comment by joscacgom** [comment]
Al final se ha optado por no realizar test del bot de telegram debido a la complejidad del mismo, no hay forma de poder comprobar que el bot responde lo que debe de responder.
