### ISSUE TITLE
INC-006: La API no proporciona un método para obtener usuarios

### ISSUE THREAD

**Issue by jvegax** [jvegax/decide#18]
| Estado  | Tipo  | Responsable            | Prioridad |
| ------- | ----- | ---------------------- | --------- |
| *En progreso* | *Funcionalidad* | *jonatep, diazzlop* |     *1*  |

### Descripción:
Se pide implementar un endpoint nuevo en la API que permita a un usuario `staff` como puede ser el admin (superusuario) obtener todos los usuarios registrados en la aplicación.

**GET /users**
- Esta acción requiere el token de un usuario `staff` como el admin
- Devuelve un array de usuarios de esta forma [ {user1}, {user2}, {user3}, ... {userN}]

### Solución Adoptada:
En curso.

### Posibles Soluciones:
- Comprobar que el usuario tiene el parametro is_staff activo para poder traer la lista completa de usuarios

**Comment by joscacgom** [comment]
Se ha renombrado la incidencia con el ID: INC-006, siguiendo la plantilla de incidencias.
