### ISSUE TITLE
INC-008: Seguir la plantilla de incidencias

### ISSUE THREAD

**Issue by joscacgom** [jvegax/decide#22]
| Estado  | Tipo  | Responsable            | Prioridad |
| ------- | ----- | ---------------------- | --------- |
| *En progreso* | *Github* | *josmarlop16* |     *1*  |

### Descripción:
Hay incidencias que no siguen la plantilla propuesta para la descripción de incidencias del proyecto. Se debe de seguir la plantilla.

### Solución Adoptada:
En curso.

### Posibles Soluciones:
- Adaptar todas las incidencias actuales, tanto cerradas como abiertas, según la plantilla proporcionada.

**Comment by josmarlop16** [comment]
Me pongo con ello!

**Comment by josmarlop16** [comment]
Se han adaptado todas las incidencias a la plantilla proporcionada de:

| Estado  | Tipo  | Responsable            | Prioridad |
| ------- | ----- | ---------------------- | --------- |
| *ESTADO* | *TIPO* | *ASIGNADOS* |     *X*  |

### Descripción:
DESCRIPCION DE LA INCIDENCIA

### Solución Adoptada:
SOLUCION QUE SE ESTA REALIZANDO

### Posibles Soluciones:
- POSIBLES SOLUCIONES PARALELAS
