### ISSUE TITLE
INC-011: Eliminar commits anteriores al inicio del proyecto

### ISSUE THREAD

**Issue by josmarlop16** [jvegax/decide#30]
| Estado  | Tipo  | Responsable            | Prioridad |
| ------- | ----- | ---------------------- | --------- |
| *Abierto* | *Github* | *josmarlop16, jvegax, ddiazlop, jonatep, LuisUsrDev, joscacgom* |     *3*  |

### Descripción:
Hay que eliminar los commits anteriores al proyectos relacionados con el inicio del proyecto. Solo deben estar aquellos posteriores a la inicializacion del proyecto.

### Solución Adoptada:
- 

### Posibles Soluciones:
-

**Comment by joscacgom** [comment]
Al final no se va a realizar, ya que eliminaríamos también todos los commits que llevamos hechos en el repo y a estas alturas no es posible hacerlo. No llegaríamos a tiempo para la entrega del mismo.
