### ISSUE TITLE
INC-012: Añadir la etiqueta "test" para los commits que sean implementaciones de test

### ISSUE THREAD

**Issue by LuisUsrDev** [jvegax/decide#31]
| Estado  | Tipo  | Responsable            | Prioridad |
| ------- | ----- | ---------------------- | --------- |
| *En progreso* | *Fallos* | *Todos* |     *1*  |

### Descripción:
Hay que utlizar una etiqueta diferente para los commits donde se implementen test

### Solución Adoptada:
Se añadirá el prefijo "test:" a los mensajes de commit que implementen test

**Comment by josmarlop16** [comment]
Esto entra dentro de la politica de commites que teniamos establecida, no se si se puede solucionar ya en los commits que no lo hayan cumplido.

**Comment by LuisUsrDev** [comment]
Se deben de añadir a la plantilla para posteriores test que se suban.

**Comment by jonatep** [comment]
Me parece bien.

**Comment by josmarlop16** [comment]
Hecho
