### ISSUE TITLE
INC-013: Parsear el mensaje que devuelve el bot con el comando /votaciones

### ISSUE THREAD

**Issue by LuisUsrDev** [jvegax/decide#32]
| Estado  | Tipo  | Responsable            | Prioridad |
| ------- | ----- | ---------------------- | --------- |
| *Cerrado* | *Fallos* | *Equipo Telegrambot* |     *1*  |

### Descripción:
Hay que parsear la respuesta que devuelve el bot cuando se lanza el /votaciones.

### Solución Adoptada:
Se ha parseado debidamente el historial de votaciones que se extraen de la BDD.

### Posibles Soluciones:
- Tratar el array que le llega al bot para convertirlo en un mensaje legible para el usuario.

**Comment by joscacgom** [comment]
Esta perfecto! A la espera del merge

**Comment by joscacgom** [comment]
Mergeado.
