### ISSUE TITLE
INC-014: Ejecutar el ./manage.py bot en el despliegue

### ISSUE THREAD

**Issue by LuisUsrDev** [jvegax/decide#33]
| Estado  | Tipo  | Responsable            | Prioridad |
| ------- | ----- | ---------------------- | --------- |
| *Cerrado* | *Funcionalidad* | *jvegax* |     *1*  |

### Descripción:
Hay que gestionar la configuración de la aplicación para que al desplegar el proyecto, se ejecute en segundo plano el bot.

### Solución Adoptada:
Para el despliegue se ha decidido desplegar el bot aparte.

### Posibles Soluciones:
- Incluir el comando ./manage.py bot dentro de la lista de comandos que se ejecutan en el despliegue.

**Comment by joscacgom** [comment]
Es necesario que se ejecute como de forma paralela
