### ISSUE TITLE
INC-002: Documentación de la API de Decide

### ISSUE THREAD

**Issue by ddiazlop** [jvegax/decide#8]
Después de la reunión de hoy creo que es factible documentar la api, ya que a varios de nosotros nos hace falta.

**Comment by jvegax** [comment]
# Problema
Desde la parte de front @josmarlop16 y yo necesitamos saber exactamente qué parámetros hay que enviar a la API para poder hacer peticiones correctamente.

Actualmente la mayoría de las peticiones siempre muestran errores de credenciales incorrectas etc, por lo que se necesita documentar exactamente qué hay que enviarle a cada petición para que funcione correctamente

# **Modulo Store**
Se necesita tener
- [ ] `POST /store/` Sirve para realizar una votación
- [ ] `GET /store/` aún no sabemos para que sirve
- [ ] `PUT /store/` no está documentada y hace falta para poder actualizar una votación e indicarle que ha dado comienzo, esto se hace actualizando el estado de `"tally" : "start"`

**Esta última petición PUT que permite actualizar el estado de una votación es muy importante**

<img width="410" alt="Captura de Pantalla 2022-11-25 a las 11 03 13" src="https://user-images.githubusercontent.com/49287932/203956717-3ce0ae35-ce4b-41d5-9d37-faa61ce1cad4.png">

# **Modulo Voting**
Se necesita tener

- [ ]  `GET /voting/` Devuelve la lista de votaciones del sistema
- [ ] `GET /voting/?id=1` Devuelve una votación dado un `id`
- [ ] `POST /voting/` Debe permitir crear una nueva votación

<img width="343" alt="Captura de Pantalla 2022-11-25 a las 11 14 34" src="https://user-images.githubusercontent.com/49287932/203959413-47d23818-13ab-4450-86a1-5cdbca355ca3.png">


@ddiazlop

**Comment by ddiazlop** [comment]
Ok, crearé una rama para esto y me encargo de hacerlo.

**Comment by ddiazlop** [comment]
Crear y obtener votaciones listo y funcionando.
![image](https://user-images.githubusercontent.com/80246584/205252668-218ff0f3-0ebd-4f81-86c1-f43a311cb3bc.png)
![image](https://user-images.githubusercontent.com/80246584/205252731-0a6de704-e125-4b3c-86d4-fa4945df4060.png)

**Comment by ddiazlop** [comment]
@jvegax Es necesario para el frontend que se pueda hacer "start" y "tally" de una votación? No están implementados en la API

**Comment by josmarlop16** [comment]
Te diria que si, y además vendria bien que se añada tambien a la api la funcion de visualizer, que es similar a la de getVoting pero con otra url

**Comment by ddiazlop** [comment]
>
